= Курс по FPGA и Clash

В данном курсе мы научимся программировать ПЛИС (Программируемые Логические Интегральные Схемы, они же FPGA). 
Для этого пройдём путь от элементарных битовых операций на https://www.chipverify.com/tutorials/systemverilog[SystemVerilog] до описания относительно нетривиальной логики на https://clash-lang.org/[Clash].

В данном курсе нас будет интересовать применение ПЛИС прежде всего для разработки и отладки внутренней логики (архитектуры) процессоров. 
По этой причине мы практически не будем уделять внимание особенностям работы с периферией (различного рода датчиками, индикаторами, которые могут подключаться или даже уже присутствуют на многих современных платах с ПЛИС).

Цель курса --- познакомиться с высокоуровневым средством программирования ПЛИС Clash.
Тем не менее, предполагается, что слушатель не знаком с ПЛИС и разработкой для них, и потому курс начнётся с основ. 
При этом, многие сопутствующие разделы, такие как основы математической логики, архитектура процессора, язык программирования Haskell (его подробное изучение) будут оставлены на самостоятельное изучение. 

В качестве введения, для ознакомления с предметом и историей вопроса, предлагается прочитать минимум первые четыре раздела статьи https://habr.com/ru/articles/801191/["Разработка цифровой аппаратуры нетрадиционным методом: Yosys, SpinalHDL, VexRiscv"].

== Рекомендуемые для изучения материалы
Для тех, кто чувствует дискомфорт при словах bash, Linux, Haskell, цифровая аппаратура, архитектура процессора, могут быть полезны следующие материалы.

. Сара Л. Харрис, Дэвид Харрис. Цифровая схемотехника и архитектура компьютера: RISC-V / пер. с англ. В. С. Яценкова, А. Ю. Романова; под ред. А. Ю. Романова. – М.: ДМК Пресс, 2021. – 810 с.: ил.
   * В идеале целиком, для наших целей стоит прочитать первые 4-5 глав.
. Денис Москвин. Функциональное программирование на языке Haskell. Курс на Stepik https://stepik.org/course/75 
   * Базовый курс, направленный на понимание функциональной парадигмы. 
   * Слегка устарел: например стандартным способом установки Haskell теперь является GHCup, а класс Monad зависит от Applicative.
. Stephen Diehl.  What I Wish I Knew When Learning Haskell. 
   * Электронная версия: https://smunix.github.io/dev.stephendiehl.com/hask/ 
   * Не книга, а скорее сборник различных библиотек и технологий, используемых в современном Haskell.
. Miran Lipovača. Learn You a Haskell for Great Good! 
   * Классическая книга по Haskell.
. Антон Холомьёв. Учебник по Haskell. 
   * Электронная версия: http://anton-k.github.io/ru-haskell-book/book/home.html
   * Ещё один учебник по Haskell. Тоже слегка устаревший.
. Richard Blum, Linux Fundamentals. 
   * Базовая книга по Linux.
