= Введение в симуляцию
:sectnums:

Как введение слова о том, что процесс создания прошивки FPGA сложен, поэтому чаще будет использоваться симуляция.

== Симулятор

Что такое симулятор.

(System)Verilog имеют симулировать open-source решения https://www.veripool.org/verilator/[Verilator] и https://steveicarus.github.io/iverilog/[Icarus Verilog], а также большинство промышленных симулятор от таких компаний как Xilinx, Altera, Lattice.

??? Абзац про разницу между Verilator и IVerilog ???

Мы будем использовать https://steveicarus.github.io/iverilog/[Icarus Verilog].

В большинстве дистрибутивов Linux Icarus Verilog присутствует{empty}footnote:[https://repology.org/project/iverilog/versions.] в репозиториях.
Тем не менее у проекта давно не выходили новые версии, а вот изменений накопилось достаточно (на момент июня 2024 года)footnote:[https://github.com/steveicarus/iverilog/discussions/1058], поэтому предлагается собрать проект самостоятельно.
Инструкция по сборке находится xref:build-icarus.adoc[здесь].

Проверим работу симулятора на _Hello, world!_.
Создадим файл `hello_world.sv` следующего содержания:
[,verilog]
----
include::example$hello_world.sv[]
----

В примерах все исполняемые файлы будут генерироваться в директории `build`.
Для корректной работы `iverilog` её необходимо заранее создать.

Для генерации исполняемого файла выполним команду:
[,console]
----
$ iverilog hello_world.sv -g2012 -o build/hello_world
----

А затем запустим с помощью:
[, console]
----
$ build/hello_world
----

Вывод должен выглядеть примерно так:
[,console]
----
Hello world!
hello_world.sv:4: $finish called at 0 (1s)
----

Теперь разберем подробнее команду для компиляции:

`hello_world.sv`::
    Имя файла, который мы собираем.
    Может быть перечислено несколько в более сложных проектах.
`-g2012`::
    Включает поддержку стандарта SystemVerilog 2012.
`-o build/hello_world`::
    Указывает путь для сохранения исполняемого файла.
