= Комбинационные схемы

__Какие-то общие слова про них. Не уверен, какие именно.__

Разберёмся же с этой концепцией на примере сумматора.
Нужно сложить два бита с переполнением.
Разберём код, реализующий эту функциональность:
[source, SystemVerilog]
.adder_plus_1_bit.sv
----
include::example$adder_plus_1_bit.sv[]
----
<1> Первый входной бит.
<2> Второй входной бит.
<3> Элемент, отвечающий за переполнение, на входе.
<4> Элемент, отвечающий за переполнение на выходе.
<5> Результат сложения.
<6> Результат сложения может зайти за пределы одного бита, тут можно сконкатенировать два элемента в один через фигурные скобки. Тогда первый совпадёт с битом переполнения, а второй -- с суммой. Важно отметить использование непрерывного присваивания через `assign`. Оно "сцепляет" элементы друг с другом, то есть при любом изменении одного элемента, изменится и другой.

Однако странно использовать встроенное сложение в своей реализации сложения.
Опираясь на https://en.wikipedia.org/wiki/Adder_(electronics)#Full_adder[выкладки умных людей], можно избавится от этого недоразумения, и предложить реализацию исключительно на логических операциях:
[source, SystemVerilog]
.adder_logic_1_bit.sv
----
include::example$adder_logic_1_bit.sv[]
----
<1> Элемент, отвечающий за переполнение, на входе.
<2> Элемент, отвечающий за переполнение на выходе.

Для проверки (конечно, просто визуальной) можно написать подобие тестбенча, подробнее о котором мы поговорим чуть позже:
[source, SystemVerilog]
.adder_logic_1_bit_tb.sv
----
include::example$adder_logic_1_bit_tb.sv[]
----
<1> Объявляем всё, что нам потребуется для работы.
<2> Задаём тестируемое устройство.
<3> Выполняем блок в начальный момент времени, можно использовать только в тестбенчах.
<4> Задаём задержку, иначе всё выведется раньше, чем успеет посчитаться.

Давайте просиммулируем полученный файл.
Тестбенч использует другой модуль, так что iverilog-у необходимо передать и его тоже:
[, bash]
----
$ iverilog adder_logic_1_bit.sv adder_logic_1_bit_tb.sv -g2012 -o build/adder_logic_1_bit_tb
----
После запустим его:
[, bash]
----
$ build/adder_logic_1_bit_tb
----
Вывод должен выглядеть так:
[, bash]
----
0 (из переполнения) 0 + 1 = 1 (0 в переполнении)
0 (из переполнения) + 1 + 1 = 0 (1 в переполнении)
1 (из переполнения) + 0 + 0 = 1 (0 в переполнении)
----
